// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCRCclw-Wme-PZoETgITJ3M3-VyNOsi8U',
    appId: '1:762136492175:web:364b627c26bff4f14bd8fa',
    messagingSenderId: '762136492175',
    projectId: 'lingoa-35d54',
    authDomain: 'lingoa-35d54.firebaseapp.com',
    storageBucket: 'lingoa-35d54.appspot.com',
    measurementId: 'G-VYQ5X63SWN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD51u5prT9s7d0UoVs59hO7p3TN_EVoaIg',
    appId: '1:762136492175:android:077ad452fbc4ec704bd8fa',
    messagingSenderId: '762136492175',
    projectId: 'lingoa-35d54',
    storageBucket: 'lingoa-35d54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAKNfEl7i2JMgVraBlpfqFNomajjKj748',
    appId: '1:762136492175:ios:00d50bf8fee859fa4bd8fa',
    messagingSenderId: '762136492175',
    projectId: 'lingoa-35d54',
    storageBucket: 'lingoa-35d54.appspot.com',
    iosClientId: '762136492175-ur200ote3mupncr7926b070sq0sbbtav.apps.googleusercontent.com',
    iosBundleId: 'com.lingoa.app',
  );
}
